In [1]:
import numpy as np

In [2]:
a=[5,4,3,2,1]

In [3]:
a

[5, 4, 3, 2, 1]

In [4]:
#converting a list into array
v= np.array(a)

In [5]:
v

array([5, 4, 3, 2, 1])

In [6]:
print(v)

[5 4 3 2 1]


In [8]:
type(v)

numpy.ndarray

In [9]:
#directly create an array
v=np.array([5,4,3,2,1])
v

array([5, 4, 3, 2, 1])

In [10]:
#create a matrix multi dimentional array
v=np.array([[5,4,3],[2,1,0],[11,15,25]])
v

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [11, 15, 25]])

In [11]:
#to know rows and column of matrix
v.shape

(3, 3)

In [13]:
v1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(v1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#matrix multiplication
mul=np.matmul(v,v1)

In [15]:
mul

array([[ 42,  54,  66],
       [  6,   9,  12],
       [246, 297, 348]])

In [16]:
mul=np.matmul(v,v1)

In [17]:
print(mul)

[[ 42  54  66]
 [  6   9  12]
 [246 297 348]]


In [18]:
#dot matrix
d=np.dot(v,v1)

In [19]:
d

array([[ 42,  54,  66],
       [  6,   9,  12],
       [246, 297, 348]])

In [20]:
v*v1

array([[  5,   8,   9],
       [  8,   5,   0],
       [ 77, 120, 225]])

In [21]:
v/v1

array([[5.        , 2.        , 1.        ],
       [0.5       , 0.2       , 0.        ],
       [1.57142857, 1.875     , 2.77777778]])

In [22]:
v+v1

array([[ 6,  6,  6],
       [ 6,  6,  6],
       [18, 23, 34]])

In [23]:
v-v1

array([[ 4,  2,  0],
       [-2, -4, -6],
       [ 4,  7, 16]])

In [25]:
v**v1

array([[          5,          16,          27],
       [         16,           1,           0],
       [   19487171, -1732076671,   766306777]], dtype=int32)

In [26]:
v//v1

array([[5, 2, 1],
       [0, 0, 0],
       [1, 1, 2]], dtype=int32)

In [27]:
#mean of matrix
np.mean(v)

7.333333333333333

In [28]:
np.mean(v1)

5.0

In [29]:
#max
np.max(v)

25

In [30]:
np.max(v1)

9

In [31]:
#min
np.min(v)

0

In [32]:
np.min(v1)

1

In [33]:
#median
np.median(v)


4.0

In [34]:
np.median(v1)

5.0

In [35]:
#max elememt of row
row_v=v[0]
row_v

array([5, 4, 3])

In [36]:
row_v=v[1]
row_v

array([2, 1, 0])

In [37]:
#Transpose of matrix rows into column and column into row
v.T

array([[ 5,  2, 11],
       [ 4,  1, 15],
       [ 3,  0, 25]])

In [38]:
v1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
#Calculation of standard deviation
np.std(v)

7.760297817881877

In [40]:
np.std(v1)

2.581988897471611

In [41]:
#square root of entire matrix
np.sqrt(v)

array([[2.23606798, 2.        , 1.73205081],
       [1.41421356, 1.        , 0.        ],
       [3.31662479, 3.87298335, 5.        ]])

In [42]:
np.sqrt(v1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [43]:
#creation of sparse matrices
#creating a 5X5 zero matrices
a=np.zeros([5,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
a.shape

(5, 5)

In [49]:
a=np.ones([5,5])
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
type(a)


numpy.ndarray

In [50]:
#identity matrix
a=[1,1,1]
v=np.diag(a)


In [51]:
v

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [52]:
a=[1,1,1,1,1,1,1,1,1,1]
v=np.diag(a)
v

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [53]:
b=[1,2,3,4,5]
v=np.diag(b)
v

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [55]:
c=[1,0,1,0]
v=np.diag(c)
v

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [56]:
v.T

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [60]:
#reshaping of a matrices
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [61]:
a.shape

(2, 5)

In [62]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
a_rshp=a.reshape(5,2)
a_rshp

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [64]:
a_rshp.T

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [65]:
#flatening of a matrice
a_flat = a.flatten()

In [66]:
a_flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a_flat.shape

(10,)

In [69]:
#vertical flatenning
a_ver_flat=a.reshape(-1,1)

In [70]:
a_ver_flat

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])